name: "Push CI - branches"

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 11

      - name: Restore local Maven repository from cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles( 'project.clj' ) }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Validate SNAPSHOT version
        env:
          SNAPSHOT_REGEX: ^[0-9]{1,2}[.][0-9]{1,2}[.][0-9]{1,3}-SNAPSHOT$
        if: github.ref != 'refs/heads/master'
        run: |
          lein pom
          export VERSION=$(less pom.xml | grep "<version>" | head -1 | cut -d ">" -f2 | cut -d "<" -f1)
          echo "Version is:" $VERSION
          if [[ !("$VERSION" =~ $SNAPSHOT_REGEX) ]]
          then
            echo "Version isn't a SNAPSHOT version:" $VERSION
            exit 0
          fi

      - name: Setup linter
        uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2023.09.07'
      - name: Lint
        run: clj-kondo --lint src test --config '{:lint-as {clojure.test.check.properties/for-all clojure.core/let}}'

  test:
    needs: build
    uses: ./.github/workflows/test.yml

  deploy:
    needs: test
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 11

      - name: Restore local Maven repository from cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles( 'project.clj' ) }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Deploy SNAPSHOT version
        env:
          SNAPSHOT_REGEX: ^[0-9]{1,2}[.][0-9]{1,2}[.][0-9]{1,3}-SNAPSHOT$
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
        run: |
          git config --global user.name "github-actions-bot"
          git config --global user.email "<>"
          lein pom
          export SNAPSHOT_VERSION=$(less pom.xml | grep "<version>" | head -1 | cut -d ">" -f2 | cut -d "<" -f1)
          echo "SNAPSHOT version is:" $SNAPSHOT_VERSION
          if [[ !("$SNAPSHOT_VERSION" =~ $SNAPSHOT_REGEX) ]]
          then
            echo "Version isn't a SNAPSHOT version:" $SNAPSHOT_VERSION ", skipping deployment to Clojars..."
            exit 0
          fi
          lein deploy
          echo "SNAPSHOT version:" $SNAPSHOT_VERSION"; commit: "${{github.sha}}"; successfully deployed to Clojars"
