name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore local Maven repository from cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles( 'project.clj' ) }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Lint
        uses: DeLaGuardo/clojure-lint-action@master
        with:
          clj-kondo-args: --lint src test
          github_token: ${{ secrets.GITHUB_TOKEN }}

  test:
    needs: build
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore local Maven repository from cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles( 'project.clj' ) }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Unit tests
        run: lein cloverage --lcov --junit
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.17
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: "target/coverage/junit.xml"
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: "target/coverage/lcov.info"
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        env:
          CLOJARS_USER: ${{ secrets.CLOJARS_USER }}
          CLOJARS_PASS: ${{ secrets.CLOJARS_PASS }}
        run: lein deploy
