name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup linter
        uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2021.06.18'
      - name: Lint
        run: clj-kondo --lint src test
      - name: Test
        run: lein test
      - name: Deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        env:
          CLOJARS_USER: ${{ secrets.CLOJARS_USER }}
          CLOJARS_PASS: ${{ secrets.CLOJARS_PASS }}
        run: lein deploy
