name: Dev

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 8
      - name: Setup linter
        uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2021.06.18'
      - name: Lint
        run: clj-kondo --lint src test --config '{:lint-as {clojure.test.check.properties/for-all clojure.core/let}}'
      - name: Test
        run: lein cloverage --lcov --junit
