name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 8
      - name: Lint
        uses: DeLaGuardo/clojure-lint-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clj-kondo-args: --lint src test --config '{:lint-as {clojure.test.check.properties/for-all clojure.core/let}}'
      - name: Test
        run: lein cloverage --lcov --junit
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.17
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: "target/coverage/junit.xml"
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: "target/coverage/lcov.info"
      - name: Deploy
        env:
          CLOJARS_USER: ${{ secrets.CLOJARS_USER }}
          CLOJARS_PASS: ${{ secrets.CLOJARS_PASS }}
        run: lein deploy
