name: Publish Build Results

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: Test results
