name: Publish Build Results

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-20.04
    steps:
      - name: Download test results artifact
        run: |
          mkdir artifacts && cd artifacts

          artifacts_url=${{ github.event.workflow_run.artifacts_url }}
          artifacts=$(gh api $artifacts_url -q '.artifacts[] | {name: .name, url: .archive_download_url}')

          IFS=$'\n'
          for artifact in $artifacts
          do
            name=$(jq -r .name <<<$artifact)
            url=$(jq -r .url <<<$artifact)
            gh api $url > "$name.zip"
            unzip -d "$name" "$name.zip"
          done
